name: npi2025
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytest
  - flask
  - requests
  - numpy
  - pandas
  - pydantic
  - uvicorn
  - fastapi
  - aiohttp
  - pip:
      - docker
      - python-dotenv
