name: npi2025
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytest
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - requests
  - flask
  - fastapi
  - uvicorn
  - aiohttp
  - pydantic
  - pip:
      - python-dotenv
      - docker
